package Pabrik.views;

import Pabrik.controllers.*;
import Pabrik.models.pabrik;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class DataPabrik extends javax.swing.JFrame {
    private final service controller = new controller();
    private int selectedId = -1;
    
    /**
     * Creates new form DataPabrik
     */
    public DataPabrik() {
        initComponents();
        showList();
        addListener();
    }
    
    private void showList(){
        DeafultTableModel model = (DefaultTableModel) jTableData.getModel();
        model.setRowCount(0);
        List<pabrik> list = controller.getAll();
        for(pabrik factory : list){
            model.addRow(new Object[]{
                pabrik.getNamaProduk();
                pabrik.getBiayaPekerja();
                pabrik.getEfisiensiProduksi();
                pabrik.getTotalBiaya();
            })
        }
    }
    
    private void resetForm(){
        jTextFieldNama.setText("");
        jTextFieldUnit.setText("");
        jTextJam.setText("");
        jTextTenaga.setText("");
        jTextFieldBahan.setText("");
    }
    
    private void addListener(){
        jButtonCreate.addActionListener(e -> {
            try{
                String namaProduk = jTextFieldNama.getText();
                int jumlahUnit = parseInt(jTextFieldUnit.getText());
                int jamKerja = parseInt(jTextJam.getText());
                int jumlahPekerja = parseInt(jTextTenaga.getText());
                int biayaBahan = parseInt(jTextFieldBahan.getText());
                double biayaPekerja = jamKerja * jumlahPekerja * 15000;
                double efisiensiProduksi = (jumlahUnit / (jamKerja * jumlahPekerja)) * 100;
                double totalBiaya = biayaBahan + biayaPekerja;
                controller.insert(new pabrik(namaProduk, biayaPekerja, efisiensiProduksi, totalBiaya));
                showList();
                resetForm();
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan!");
                return;
            }
        });
        jButtonEdit.addActionListener(e->{
            if(selectedId == -1){
                JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu!");
                return;
            }
            try{
                String namaProduk = jTextFieldNama.getText();
                int jumlahUnit = parseInt(jTextFieldUnit.getText());
                int jamKerja = parseInt(jTextJam.getText());
                int jumlahPekerja = parseInt(jTextTenaga.getText());
                int biayaBahan = parseInt(jTextFieldBahan.getText());
                double biayaPekerja = jamKerja * jumlahPekerja * 15000;
                double efisiensiProduksi = (jumlahUnit / (jamKerja * jumlahPekerja)) * 100;
                double totalBiaya = biayaBahan + biayaPekerja;
                controller.insert(new pabrik(namaProduk, biayaPekerja, efisiensiProduksi, totalBiaya));
                showList();
                resetForm(); 
                JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan!");
                return;
            }
        });
        jButtonDelete.addActionListener(e->{
            if(selectedId == -1){
                JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu!");
                return;
            }
            controller.delete(selectedId);
            showList();
            resetForm(); 
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableData = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabelUnit = new javax.swing.JLabel();
        jTextFieldUnit = new javax.swing.JTextField();
        jLabelJam = new javax.swing.JLabel();
        jTextJam = new javax.swing.JTextField();
        jLabelTenaga = new javax.swing.JLabel();
        jTextTenaga = new javax.swing.JTextField();
        jTextFieldBahan = new javax.swing.JTextField();
        jLabelBahan = new javax.swing.JLabel();
        jButtonCreate = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        jTableData.setBackground(new java.awt.Color(102, 102, 102));
        jTableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Produk", "Biaya Tenaga Kerja", "Efisiensi Produksi", "Total Biaya Produksi"
            }
        ));
        jScrollPane1.setViewportView(jTableData);

        jLabel1.setText("Nama Produk");

        jLabelUnit.setText("Jumlah Unit");

        jTextFieldUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUnitActionPerformed(evt);
            }
        });

        jLabelJam.setText("Jam Kerja");

        jLabelTenaga.setText("Jumlah Tenaga Kerja");

        jLabelBahan.setText("Biaya Bahan Baku");

        jButtonCreate.setText("Create");
        jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateActionPerformed(evt);
            }
        });

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabelUnit)
                                    .addComponent(jLabelJam)
                                    .addComponent(jLabelTenaga)
                                    .addComponent(jLabelBahan))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextTenaga, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextJam, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldBahan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonCreate)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEdit))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jButtonDelete)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelUnit)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelJam))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextTenaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTenaga))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldBahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBahan))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCreate)
                            .addComponent(jButtonEdit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDelete)))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUnitActionPerformed

    private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCreateActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPabrik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPabrik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPabrik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPabrik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPabrik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBahan;
    private javax.swing.JLabel jLabelJam;
    private javax.swing.JLabel jLabelTenaga;
    private javax.swing.JLabel jLabelUnit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableData;
    private javax.swing.JTextField jTextFieldBahan;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldUnit;
    private javax.swing.JTextField jTextJam;
    private javax.swing.JTextField jTextTenaga;
    // End of variables declaration//GEN-END:variables
}
